credentials/urls.py
from django.urls import path
from . import views
app_name='credentials'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('account/',views.account,name='account'),


 ]

movie_app/urls.py
from django.urls import path
from . import views
app_name='movie_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('movi/',views.movi,name='movi'),
    path('add/', views.add_movie, name='add_movie'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    # path('revw/',views.revw,name='revw'),
    # path('reviewpage/',views.reviewpage,name='reviewpage'),
    path('search/', views.search, name='search')


]

movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls')),
    path('credentials/',include('credentials.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

credentials/models.py
from django.db import models

# Create your models here.
# class User(models.Model):
#     username = models.CharField(max_length=120)
#     first_name = models.CharField(max_length=120)
#     last_name = models.CharField(max_length=120)
#     password = models.CharField(max_length=120)

movie_app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    description=models.TextField()
    username=models.CharField(max_length=250)
    year=models.TextField()
    trailer=models.URLField(blank=True,null=True)
    img=models.ImageField(upload_to='gallery')
    moviereview=models.CharField(max_length=250)

    def __str__(self):
        return self.name

# class Review(models.Model):
#     moviename = models.CharField(max_length=250)
#     moviereview = models.CharField(max_length=250)
#     author = models.CharField(max_length=250)

    # def __str__(self):
    #     return self.moviename

credentials/forms.py
from django import forms

movie_app/forms.py
from django import forms
from . models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','description','year','username','trailer','img']

class ReviewForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['moviereview']

credentials/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect



# Create your views here.
def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid credentials')
            return redirect('credentials:login')
    return render(request,"login.html")
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username taken")
                return redirect('/credentials/register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"email already taken")
                return redirect('/credentials/register')
            else:
                user = User.objects.create_user(username=username, password=password, first_name=first_name,last_name=last_name, email=email)
                user.save();
                print("user created")
                return redirect('credentials:login')
        else:
            messages.info(request,"password not matching")
            return redirect('/credentials/register')
        return redirect('/')
    return render(request, "register.html")
def logout(request):
    auth.logout(request)
    return redirect('/')

def account(request):
    if request.user.is_authenticated:
        pass
    else:
        return redirect('/')
    return render(request,'profile.html')

movie_app/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm
from .forms import ReviewForm

# Create your views here.
def index(request):
    return render(request,'index.html')


def movi(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'movie.html',context)

def add_movie(request):
    if request.method=="POST":
        name = request.POST.get('name',)
        description = request.POST.get('description',)
        trailer = request.POST.get('trailer')
        img = request.FILES['img']
        year = request.POST.get('year',)
        username = request.POST.get('username',)
        movie = Movie(name=name,description=description,trailer=trailer,img=img,username=username)
        movie.save()
        return redirect('/movi')
    return render(request,'add.html')

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def update(request,id):
    movie=Movie.objects.get(id=id)
    if request.user.is_authenticated:
      form=MovieForm(request.POST or None,request.FILES,instance=movie)
      if form.is_valid():
        form.save()
        return redirect('/')
    else:
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
      if request.method=="POST":
          movie=Movie.objects.get(id=id)
          movie.delete()
          return redirect('/')
      return render(request,'delete.html')

def search(request):
  query = request.GET.get('query')
  movies = Movie.objects.filter(
    name__contains=query
  )
  return render(request, 'search.html', {'movies': movies})

templates/action.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
     <div class="card " style="width: 24rem;">
         <ul class="list-group list-group-flush">
    <input type="text" name="name" placeholder="enter your movie name"><br>
    <input type="file" name="img"><br>
    <input type="text" name="description" placeholder="enter the desription"><br>
             <input type="url" name="trailer" placeholder="enter trailer link"><br>
    <input type="number" name="year" placeholder="enter the release date"><br>
    <input type="text" name="username" placeholder="enter your username"><br>
    <input type="submit">
         </ul>
     </div>

</form>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'edit.css' %}">
</head>
<body>
<nav class="navbar navbar-light bg-dark">
  <a class="navbar-brand" href="#">
   our recomended movies

      <nav class="nav justify-content-end">
           <span class="navbar-text">
      <a href="{% url 'movie_app:add_movie' %}"><span class="padding_left_15 margin-right:10px;"><button type="button" class="btn btn-outline-danger mr-3">+movies</button></span></a>
      <a href="{% url 'movie_app:index' %}"><span class="padding_left_15"><button type="button" class="btn btn-outline-danger mr-3">home</button></span></a>
<!--        <form action="/search/" method="GET">-->
<!--  <input type="text" name="query">-->
<!--  <input type="submit" value="Search">-->
<!--</form>-->
       <form action="/search/" method="GET" class="d-flex" role="search">
        <input class="form-control mr-2" type="search" name="query" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-danger mr-2" type="submit" value="Search">Search</button>
      </form>
           </span>
      </nav>
  </a>
</nav>
<br>

{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete the movie
    <input type="submit">
</form>

</body>
</html>

templates/detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .link {
        margin-left:20px;
        float:left;
        }

    </style>
</head>
<body>
{% block body %}
<div class="card" style="width: 400px; height:700px;">
  <img src="{{movie.img.url}}" style="width:400px; height:350px;" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{movie.name}}</h5>
    <p class="card-text">{{movie.description}}</p>
      <p class="card-text"><a href="{{movie.trailer}}"><button type="button" class="btn btn-danger">trailer</button></a></p>
    </div>

  <div class="card-body">
      <a href="#"><span class="padding_left_15"><button type="button" class="btn btn-outline-danger mr-3">+reviews</button></span></a>
      <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">edit</a>
      <a class="btn btn-warning" href="{% url 'movie_app:delete' movie.id %}">delete</a>


  </div>





{% endblock %}
</body>
</html>

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><h2>login<h2></title>
</head>
<body>
<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="UserName"><br>
     <input type="password" name="password" placeholder="Enter your password"><br>
    <input type="submit">
</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</body>
</html>

templates/movie.html
{% extends 'base.html'%}

{% block body %}

<div class="containter">
    <div class="row mx-auto" style="gap:50px;">
        {% for i in movie_list %}
        <div class="col-md-2">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" width="100px" height="200px;">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.year}}</p>
      <a href="{% url  'movie_app:detail' i.id %}" class="btn btn-danger mr-2">details</a>
      <h7 class="card-text"> uploaded by:{{i.username}}</h7>
  </div>
</div>
        </div>

        {% endfor %}

    </div>
</div>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
      <li class="list-group-item"><p><h5>   Your Profile</h5></p></li>
    <li class="list-group-item">username:{{user.username}}</li>
    <li class="list-group-item">name:{{user.first_name}}</li>
    <li class="list-group-item">second name:{{user.last_name}}</li>
  </ul>
</div>

{% endblock %}

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> registeration portal</h1>
<form action="{% url 'credentials:register' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="UserName"><br><br>
     <input type="text" name="first_name" placeholder="Enter your name"><br><br>
     <input type="text" name="last_name" placeholder="Enter second name"><br><br>
     <input type="email" name="email" placeholder="Enter your email address"><br><br>
     <input type="password" name="password" placeholder="Enter password"><br><br>
     <input type="password" name="password1" placeholder="Confirm password"><br><br>
    <input type="submit">
</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</body>
</html>

templates/review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
<!--        body {-->
<!--      background-image: url('static/images/titanic.png');-->
<!--      background-size: cover;-->
<!--      background-position: center;-->
<!--     }-->

<!--    .content {-->
<!--      color: white; /* Example text color for better visibility on the background */-->
<!--      text-align: center;-->
<!--      padding:20px;-->
<!--        }-->

    </style>
</head>
<body>
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<h1> Add Your Review</h1>
<form action="{% url 'movie_app:revw'  %}" method="post">
    {% csrf_token %}
     <input type="text" name="moviereview" placeholder="Enter your review"><br><br>
    <input type="submit">
</form>

</body>
</html>

templates/reviewpage.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
.body{
background-color:maroon;
}
{% block body %}
{% for i in review %}
<div class="card" style="width: 28rem; border:3px solid #ccc;">
  <div class="card-body">
    <h5 class="card-title">movie name:{{i.name}}</h5>
    <p class="card-text">review:{{i.review}}</p>
       <p class="card-text">by:{{user.username}}</p>
    </div>
</div>
<br>
{% endfor %}
{% endblock %}
</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% block body %}


<div class="containter">
     <div class="row">
         {% for i in movies %}
         <div class="col-md-3">
             <div class="card" style="width: 18rem;">
   <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="200px;">
   <div class="card-body">
     <h5 class="card-title">{{i.name}}</h5>
     <p class="card-text">{{i.year}}</p>
       <a href="{% url  'movie_app:detail' i.id %}" class="btn btn-primary">details</a>
       <h6 class="card-text"> uploaded by:{{i.username}}</h6>
   </div>
 </div>
         </div>
         {% endfor %}
     </div>
 </div>
<br>
{% endblock %}
 
 